displayName=Learner ToB
author=macflag
description=Highly Customizable Theatre of Blood Helper Focused on Learners
tags=tob,theatre,blood,raid,learner,pvm,gear,setup
plugins=com.learnertob.LearnerTobPlugin
version=1.1
build=standard